# Generated by Django 5.2.8 on 2025-12-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cso_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csoevent",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="csoevent",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
